version: '2'
volumes:
  service_roamer:
  harness_cinny:
  daemon_synapse:
services:
  daemon_caddy:
    build: ./daemon/caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
    volumes:
      - harness_cinny:/harness/cinny
  daemon_next:
    build: ./daemon/next
    restart: always
    expose:
      - "80"
    volumes:
      - service_roamer:/usr/src/app/service/roamer
      - harness_cinny:/usr/src/app/harness/cinny
  service_roamer:
    build: ./service/roamer
    network_mode: host
    volumes:
      - service_roamer:/roamer
  harness_cinny:
    build: ./harness/cinny
    volumes:
      - harness_cinny:/src/dist
  daemon_synapse:
    build: ./daemon/synapse
    restart: "on-failure"
    expose:
      - "8008"
    volumes:
      - daemon_synapse:/data
  service_wifi-connect:
    build: ./service/wifi-connect
    network_mode: "host"
    labels:
      io.balena.features.dbus: '1'
    cap_add:
      - NET_ADMIN
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"

  hostname:
    image: bh.cr/g_tomas_migone1/hostname
    restart: no                               # Required to avoid container restarting indefinitely
    labels:
      io.balena.features.supervisor-api: 1    # Required to interact with the supervisor
    environment:
      SET_HOSTNAME: home