version: '2'
services:
  daemon_next:
    privileged: true
    user: root
    build:
      context: ./daemon/next
      dockerfile: Dockerfile.local
    volumes:
      - ./daemon/next/:/usr/src/app
      - ./daemon/next/.next:/usr/src/app/.next
      - ./daemon/next/node_modules:/usr/src/app/node_modules
      - service_hostname_local:/usr/src/app/service/hostname
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.local
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    network_mode: host
    privileged: true
    volumes:
      - ./app:/usr/src/app
      - ./app/node_modules:/usr/src/app/node_modules
  service_hostname:
    build:
      context: ./service/hostname
      dockerfile: Dockerfile.local
    environment:
      SET_HOSTNAME: setup
    volumes:
      - service_hostname_local:/service/hostname
volumes:
  service_hostname_local:
