version: '2'
volumes:
  service_upnp:
  service_hostname:
  harness__cinny:
  daemon_synapse:
  proxy_nm: 
  service_yggdrasil:
  service_yggdrasil_sock:
  shared_etc: 
services:
  daemon_caddy:
    build: ./daemon/caddy
    restart: always
    network_mode: host
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
      - "4000:4000"
      - "4001:4001"
    volumes:
      - harness__cinny:/harness/cinny
  daemon_next:
    build: ./daemon/next
    restart: always
    network_mode: host
    expose:
      - "80"
    volumes:
      - service_upnp:/usr/src/app/service/upnp
      - service_hostname:/usr/src/app/service/hostname
      - harness__cinny:/usr/src/app/harness/cinny
  service_upnp:
    build: ./service/upnp
    network_mode: host
    volumes:
      - service_upnp:/upnp
  service_wifi-connect:
    build: ./service/wifi-connect
    network_mode: "host"
    labels:
      io.balena.features.dbus: '1'
    cap_add:
      - NET_ADMIN
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"

  service_hostname:
    build: ./service/hostname
    restart: "no" # Required to avoid container restarting indefinitely
    network_mode: host
    labels:
      io.balena.features.supervisor-api: 1 # Required to interact with the supervisor
    environment:
      SET_HOSTNAME: setup
    volumes:
      - service_hostname:/service/hostname
  
  daemon_proxy:
    build: ./lib
    labels:
      io.balena.features.dbus: '1'
    privileged: true
    network_mode: host
    restart: always
    volumes:
      - service_upnp:/proxy/upnp
    expose:
      - "8000"
  # These will eventually live in an inherited project, but until they have a home they are saved here
  service_yggdrasil:
    # https://stackoverflow.com/a/37090165
    build:
      context: ./service/yggdrasil/
      dockerfile: ./contrib/docker/Dockerfile
    privileged: true
    network_mode: host
    expose:
      - "9001"
    volumes:
      - service_yggdrasil:/etc/yggdrasil-network
      - service_yggdrasil_sock:/var/run/
  service_yggdrasil-peers:
    build: ./service/yggdrasil-peers
    privileged: true
    network_mode: host
    volumes:
      - service_yggdrasil_sock:/var/run/
      - shared_etc:/peers/
    # restart: "always"
  harness__cinny:
    build: ./harness/cinny
    volumes:
      - harness__cinny:/src/dist
  daemon_synapse:
    build: ./daemon/synapse
    restart: "on-failure"
    network_mode: host
    expose:
      - "8008"
    ports: 
      - "8008:8008"
    volumes:
      - daemon_synapse:/data
      - shared_etc:/etc
