version: '2'
services:
  daemon_next:
    command: "npm run dev"
    build:
      context: ./daemon/next
      dockerfile: Dockerfile.local
    volumes:
      - ./daemon/next/:/usr/src/app
      - ./daemon/next/.next:/usr/src/app/.next
      - next_modules:/usr/src/app/node_modules
  service_hostname:
    build:
      context: ./service/hostname
      dockerfile: Dockerfile.local
volumes:
  next_modules:
